version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6:
          context: traces
      - test-3.5:
          context: traces
      - test-3.7:
          context: traces
      - test-3.8:
          context: traces
jobs:
  test-3.6: &test-template
    docker:
     - image: circleci/python:3.6-buster
    filters:
      branches:
        only:
          - dev
          - master
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv || virtualenv --no-site-packages venv
            . venv/bin/activate
            pip install -e .[test]
      - save_cache:
          key: cache-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            nosetests --with-coverage --cover-package=traces
            coveralls
            pycodestyle traces/
	    pytest --mpl tests/test_plot.py
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-buster
  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7-buster
  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8-buster
